config/routes.rb
Rails.application.routes.draw do
  
  resources :vagues
 
  resources :provinces
  get '/direct_message', to: 'bot_twitter#direct_message'
  get '/get_followers', to: 'bot_twitter#get_followers'
  get '/get_screen_name', to: 'bot_twitter#get_screen_name'
  get '/send_public_tweet', to: 'bot_twitter#send_public_tweet'
  get '/send_private_tweet', to: 'bot_twitter#send_private_tweet'
  resources :levels
  devise_for :users
  root 'home#index'
  resources :etablissements
  get 'etablissements/:id/likes', to: 'etablissements#likes', as: :likes
  resources :articles
  resources :filieres
  resources :niveaus
  resources :niveausups
  resources :associate_filiere_etabs
  resources :inscriptions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :etablissement
end

app/models/etablissement.rb
class Etablissement < ApplicationRecord
    has_many :associate_user_etabs
    has_many :user, through: :associate_user_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    has_attached_file :dossier_a_fournir    
    validates_attachment :dossier_a_fournir, content_type: { content_type: "application/pdf" }
    
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_attached_file :image_etablissement, styles: { large: "603.33x426.67>", thumb: "450x300>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image_etablissement, content_type: /\Aimage\/.*\z/

    has_many :associate_filiere_etabs
    has_many :filiere, through: :associate_filiere_etabs

    has_many :associate_niveau_etabs
    has_many :niveau, through: :associate_niveau_etabs

    has_many :articles

    has_many :vagues

    # etablissemnt followable
    acts_as_followable
    # on peut liker etab
    acts_as_likeable

    belongs_to :province
    
end

app/models/filiere.rb
class Filiere < ApplicationRecord
    has_many :associate_filiere_etabs
    has_many :etablissement, through: :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    validates :nom, presence: true
    validates :nom, uniqueness: true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :user
    belongs_to :etablissement
    belongs_to :vague
    belongs_to :filiere
    belongs_to :province
    belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/niveau.rb
class Niveau < ApplicationRecord
    has_many :associate_niveau_etabs
    has_many :etablissement, through: :associate_niveau_etabs
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etablissements
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/role.rb
class Role < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # inclusion de uploader
  mount_uploader :image, ImageUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :associate_user_etabs
  has_many :etablissement, through: :associate_user_etabs

  has_many :inscriptions
  has_many :etablissement, through: :inscriptions

  has_many :vague, through: :inscriptions

  has_many :filiere, through: :inscriptions

  has_many :province, through: :inscriptions

  has_many :level, through: :inscriptions
  
  #validation image
  #has_attached_file :image, 
  #validates_attachment :image, content_type: ["image/jpeg", "image/png", "image/gif"]
#  size: { in: 0..10.kilobytes }
  

  #user can follows
  acts_as_follower
  # liker etab
  acts_as_liker
end

app/models/vague.rb
class Vague < ApplicationRecord
    
  has_many :inscriptions
  has_many :user, through: :inscriptions

  belongs_to :etablissement
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		UserMailer.welcome_email(nil).deliver_now
		if user_signed_in?
			if current_user.role=="responsable"
				session[:responsable] = 1
				@a = AssociateUserEtab.all
				#test = false
				@a.each do |assoc|
					if assoc.user == current_user
						# la personne a déjà un étab /  rédiriger vers son établissement
						#id de son etablissement
						#test = true
						#@id_etab = assoc.etablissement.i
						#test=true
						session[:etab_id] = assoc.etablissement.id
						#session[:etab_id] =  Etablissement.find_by(responsable_id: current_user.id).id
					end
				end
				
			end
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/niveaus_helper.rb
module NiveausHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/home/index.html.erb
 <div class="home-search">
    <div class="main search-form v2">
       <div class="container">
          <div class="row justify-content-md-center">
             <div class="col-md-12 col-lg-10">
                <div class="heading">
                   <h2>Trouvez votre prochaine école</h2>
                   <h3>E-anatra est la plateforme qu'il vous faut</h3>
                </div>

                <form action="etablissements/", method="GET">
                   <div class="row justify-content-md-center">
                      <div class="col-md-9 col-lg-8">
                         <div class="input-group input-group-lg">
                            <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
                            <input type="text" class="form-control" placeholder="Etablissements, lieux ...">
                            <span class="input-group-append">
                            <button class="btn btn-primary btn-lg" type="submit">Recherche</button>
                            </span>
                         </div>
                      </div>
                   </div>
                </form>

             </div>
          </div>
       </div>
    </div>
 </div>
 <div id="content" class="pt0 pb0">
    <div class="feature-box centered">
       <div>
          <div class="container">
             <div class="row justify-content-md-center">
                <div class="col col-lg-12 col-xl-10">
                   <div class="row">
                      <div class="col-md-4">
                         <div class="content-box">
                            <div class="image"> <img src="img/demo/icons/1.png" width="100" alt=""> </div>
                            <h4>Lifestyle</h4>
                            <div class="caption">Create your best-ever home with the latest trends in renovating, decorating and more.</div>
                            <div class="button"><a href="index.html#">FIND YOUR INSPIRATION</a></div>
                         </div>
                      </div>
                      <div class="col-md-4">
                         <div class="content-box">
                            <div class="image"> <img src="img/demo/icons/2.png" width="100" alt=""> </div>
                            <h4>International</h4>
                            <div class="caption">Thinking abroad? You can now dream and discover international properties.</div>
                            <div class="button"><a href="index.html#">CHOOSE A COUNTRY</a></div>
                         </div>
                      </div>
                      <div class="col-md-4">
                         <div class="content-box">
                            <div class="image"> <img src="img/demo/icons/3.png" width="100" alt=""> </div>
                            <h4>Sell</h4>
                            <div class="caption">Understand your local market, learn how to get the best price for your property and find agents in your area.</div>
                            <div class="button"><a href="index.html#">EXPLORE NOW</a></div>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>



      <div class="feature-box gray centered">
       <div>
          <div class="container">
             <div class="row justify-content-md-center">
                <div class="col col-lg-12 col-xl-10">
                   <div class="main-title"><span>Quelque un de nos établissements </span></div>
                   <div class="item-listing grid mb50">
                      <div class="row">

                        <!-- 3 ETABLISSEMENT HOME -->
                        <% @etablissements.each do |etab| %>
                        <a href="<%= etablissement_path(etab.id) %>">
                          <div class="col-md-4">
                            <div class="item">
                              <div class="item-image">
                                  <%= image_tag etab.image_etablissement.url(:thumb), class: "img-fluid" %>
                                  <% if etab.category? %>
                                  <div class="item-badges">
                                    <div class="item-badge-left"><%= etab.category %></div>
                                  </div>
                                  <% end %>
                                <a href="<%= etablissement_path(etab.id) %>"></a>
                              </div>
                            <div class="item-info">
                              <h3 class="item-title"><%= etab.nom %></h3>
                              <div class="item-location"><i class="fa fa-map-marker"></i>&nbsp;
                                <%= etab.adress %></div>
                                 <a href="<%= likes_path(etab)%>">
                              <div class="item-details-i"><i class="fa fa-thumbs-up"></i>&nbsp;
                              <%= etab.likers_count %> </div>
                                 </a>
                            </div>
                            </div>
                          </div>
                        </a>
                        <% end %>
                        <!-- 3 ETABLISSEMENT HOME END -->

                      </div>
                   </div>
                   <div class="text-center"><a href="/etablissements" class="btn btn-xlg btn-link">Voir tout</a></div>
                </div>
             </div>
          </div>
       </div>
    </div>





    <div class="feature-box centered">
       <div>
          <div class="container">
             <div class="row justify-content-md-center">
                <div class="col col-lg-12 col-xl-10">
                   <div class="main-title"><span>What our clients say</span></div>
                   <div class="swiper-container testimonials">
                      <div class="swiper-wrapper">
                         <div class="swiper-slide">
                            <div class="item content-box centered">
                               <div class="image"> <img class="rounded-circle" src="img/demo/profile.jpg" width="180" alt=""> </div>
                               <h4>Thank you for your quick and clear responses. They are much appreciated. This was a site that needed to go up fast and it has – customizations and all!</h4>
                               <div class="caption">The Brown Family</div>
                            </div>
                         </div>
                         <div class="swiper-slide">
                            <div class="item content-box centered">
                               <div class="image">
                                  <img class="rounded-circle" src="img/demo/profile2.jpg" width="180" alt="">
                                  <h4>Thank you for your quick and clear responses. They are much appreciated. This was a site that needed to go up fast and it has – customizations and all!</h4>
                                  <div class="caption">The Brown Family</div>
                               </div>
                            </div>
                         </div>
                         <div class="swiper-slide">
                            <div class="item content-box centered">
                               <div class="image">
                                  <img class="rounded-circle" src="img/demo/profile3.jpg" width="180" alt="">
                                  <h4>Thank you for your quick and clear responses. They are much appreciated. This was a site that needed to go up fast and it has – customizations and all!</h4>
                                  <div class="caption">The Brown Family</div>
                               </div>
                            </div>
                         </div>
                      </div>
                      <!-- Add Arrows -->
                      <div class="swiper-button-next"></div>
                      <div class="swiper-button-prev"></div>
                   </div>
                   <script>
                      var swiper = new Swiper('.swiper-container', {
                        loop: true,
                        centeredSlides: true,
                          autoplay: {
                          delay: 5000,
                          disableOnInteraction: false,
                        },
                        pagination: {
                          el: '.swiper-pagination',
                          clickable: true,
                        },
                        navigation: {
                          nextEl: '.swiper-button-next',
                          prevEl: '.swiper-button-prev',
                        },
                      });
                            
                   </script> 
                </div>
             </div>
          </div>
       </div>
    </div>