config/routes.rb
Rails.application.routes.draw do
  
  resources :vagues
 
  resources :provinces
  get '/direct_message', to: 'bot_twitter#direct_message'
  get '/get_followers', to: 'bot_twitter#get_followers'
  get '/get_screen_name', to: 'bot_twitter#get_screen_name'
  get '/send_public_tweet', to: 'bot_twitter#send_public_tweet'
  get '/send_private_tweet', to: 'bot_twitter#send_private_tweet'
  resources :levels
  devise_for :users
  root 'home#index'
  resources :etablissements
  get 'etablissements/:id/likes', to: 'etablissements#likes', as: :likes
  resources :articles
  resources :filieres
  resources :niveaus
  resources :niveausups
  resources :associate_filiere_etabs
  resources :inscriptions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :etablissement
end

app/models/etablissement.rb
class Etablissement < ApplicationRecord
    has_many :associate_user_etabs
    has_many :user, through: :associate_user_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    has_attached_file :dossier_a_fournir    
    validates_attachment :dossier_a_fournir, content_type: { content_type: "application/pdf" }
    
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_attached_file :image_etablissement, styles: { large: "603.33x426.67>", thumb: "450x300>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image_etablissement, content_type: /\Aimage\/.*\z/

    has_many :associate_filiere_etabs
    has_many :filiere, through: :associate_filiere_etabs

    has_many :associate_niveau_etabs
    has_many :niveau, through: :associate_niveau_etabs

    has_many :articles

    has_many :vagues

    # etablissemnt followable
    acts_as_followable
    # on peut liker etab
    acts_as_likeable

    belongs_to :province
    
end

app/models/filiere.rb
class Filiere < ApplicationRecord
    has_many :associate_filiere_etabs
    has_many :etablissement, through: :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    validates :nom, presence: true
    validates :nom, uniqueness: true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :user
    belongs_to :etablissement
    belongs_to :vague
    belongs_to :filiere
    belongs_to :province
    belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/niveau.rb
class Niveau < ApplicationRecord
    has_many :associate_niveau_etabs
    has_many :etablissement, through: :associate_niveau_etabs
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etablissements
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/role.rb
class Role < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # inclusion de uploader
  mount_uploader :image, ImageUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :associate_user_etabs
  has_many :etablissement, through: :associate_user_etabs

  has_many :inscriptions
  has_many :etablissement, through: :inscriptions

  has_many :vague, through: :inscriptions

  has_many :filiere, through: :inscriptions

  has_many :province, through: :inscriptions

  has_many :level, through: :inscriptions
  
  #validation image
  #has_attached_file :image, 
  #validates_attachment :image, content_type: ["image/jpeg", "image/png", "image/gif"]
#  size: { in: 0..10.kilobytes }
  

  #user can follows
  acts_as_follower
  # liker etab
  acts_as_liker
end

app/models/vague.rb
class Vague < ApplicationRecord
    
  has_many :inscriptions
  has_many :user, through: :inscriptions

  belongs_to :etablissement
end

app/controllers/vagues_controller.rb
class VaguesController < ApplicationController
  
  # GET /vagues
  # GET /vagues.json
  def index
    @vagues = Vague.all
  end

  # GET /vagues/1
  # GET /vagues/1.json
  def show
  end

  # GET /vagues/new
  def new
    @vague = Vague.new
  end

  # GET /vagues/1/edit
  def edit
  end

  # POST /vagues
  # POST /vagues.json
  def create
    v = Vague.new()
    v.rentree = "1-32018"# params([:vague][:rentree])
    v.etablissement = Etablissement.find(params[:vague][:etablissement_id])
    redirect_to vagues_path
  end

  # PATCH/PUT /vagues/1
  # PATCH/PUT /vagues/1.json
  def update
    
  end

  # DELETE /vagues/1
  # DELETE /vagues/1.json
  def destroy
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/niveaus_helper.rb
module NiveausHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/vagues/edit.html.erb
<h1>Editing Vague</h1>

<%= render 'form', vague: @vague %>

<%= link_to 'Show', @vague %> |
<%= link_to 'Back', vagues_path %>

app/views/vagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vagues</h1>

<table>
  <thead>
    <tr>
      <th>Rentree</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vagues.each do |vague| %>
      <tr>
        <td><%= vague.rentree %></td>
        <td><%= vague.status %></td>
        <td><%= link_to 'Show', vague %></td>
        <td><%= link_to 'Edit', edit_vague_path(vague) %></td>
        <td><%= link_to 'Destroy', vague, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vague', new_vague_path %>

app/views/vagues/new.html.erb
<div class="container">
    <%= form_for @vague  do |f| %>

        <fieldset class="form-group">
            <label for="date">Rentree</label>
            <%= f.date_field :rentree %>
        </fieldset>

        <fieldset class="form-group">
            <label for="etabmissement">Etablissement</label>
            <%= f.collection_select :etablissement_id, Etablissement.order(:nom), :id, :nom, include_blank: true %>
        </fieldset>

        <%= f.submit "Ajouter", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/vagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rentree:</strong>
  <%= @vague.rentree %>
</p>

<p>
  <strong>Status:</strong>
  <%= @vague.status %>
</p>

<%= link_to 'Edit', edit_vague_path(@vague) %> |
<%= link_to 'Back', vagues_path %>