config/routes.rb
Rails.application.routes.draw do
  
  resources :vagues
 
  resources :provinces
  get '/direct_message', to: 'bot_twitter#direct_message'
  get '/get_followers', to: 'bot_twitter#get_followers'
  get '/get_screen_name', to: 'bot_twitter#get_screen_name'
  get '/send_public_tweet', to: 'bot_twitter#send_public_tweet'
  get '/send_private_tweet', to: 'bot_twitter#send_private_tweet'
  resources :levels
  devise_for :users
  root 'home#index'
  resources :etablissements
  get 'etablissements/:id/likes', to: 'etablissements#likes', as: :likes
  resources :articles
  resources :filieres
  resources :niveaus
  resources :niveausups
  resources :associate_filiere_etabs
  resources :inscriptions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :etablissement
end

app/models/etablissement.rb
class Etablissement < ApplicationRecord
    has_many :associate_user_etabs
    has_many :user, through: :associate_user_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    has_attached_file :dossier_a_fournir    
    validates_attachment :dossier_a_fournir, content_type: { content_type: "application/pdf" }
    
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_attached_file :image_etablissement, styles: { large: "603.33x426.67>", thumb: "450x300>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image_etablissement, content_type: /\Aimage\/.*\z/

    has_many :associate_filiere_etabs
    has_many :filiere, through: :associate_filiere_etabs

    has_many :associate_niveau_etabs
    has_many :niveau, through: :associate_niveau_etabs

    has_many :articles

    has_many :vagues

    # etablissemnt followable
    acts_as_followable
    # on peut liker etab
    acts_as_likeable

    belongs_to :province
    
end

app/models/filiere.rb
class Filiere < ApplicationRecord
    has_many :associate_filiere_etabs
    has_many :etablissement, through: :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions

    validates :nom, presence: true
    validates :nom, uniqueness: true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/inscription.rb
class Inscription < ApplicationRecord
    belongs_to :user
    belongs_to :etablissement
    belongs_to :vague
    belongs_to :filiere
    belongs_to :province
    belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :associate_filiere_etabs

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/niveau.rb
class Niveau < ApplicationRecord
    has_many :associate_niveau_etabs
    has_many :etablissement, through: :associate_niveau_etabs
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :etablissements
    validates :nom, presence: true
    validates :nom, uniqueness: true

    has_many :inscriptions
    has_many :user, through: :inscriptions
end

app/models/role.rb
class Role < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # inclusion de uploader
  mount_uploader :image, ImageUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :associate_user_etabs
  has_many :etablissement, through: :associate_user_etabs

  has_many :inscriptions
  has_many :etablissement, through: :inscriptions

  has_many :vague, through: :inscriptions

  has_many :filiere, through: :inscriptions

  has_many :province, through: :inscriptions

  has_many :level, through: :inscriptions
  
  #validation image
  #has_attached_file :image, 
  #validates_attachment :image, content_type: ["image/jpeg", "image/png", "image/gif"]
#  size: { in: 0..10.kilobytes }
  

  #user can follows
  acts_as_follower
  # liker etab
  acts_as_liker
end

app/models/vague.rb
class Vague < ApplicationRecord
    
  has_many :inscriptions
  has_many :user, through: :inscriptions

  belongs_to :etablissement
end

app/controllers/niveaus_controller.rb
class NiveausController < ApplicationController
  def index
    @niveaux = Niveau.all
  end

  def show
    @niveau = Niveau.find(params[:id])
  end

  def edit
    @niveau = Niveau.find(params[:id])
  end

  def new
    @niveau = Niveau.new
  end

  def create
    @niveau = Niveau.new(niveau: params[:niveau][:niveau], place: params[:niveau][:place].to_i)
    if @niveau.save
      flash[:success] = "Création niveau avec succès"
      redirect_to niveaus_path
    else
      flash[:error] = "Champ invalid !"
      redirect_to new_niveau_path
    end
  end

  def update
    @niveau = Niveau.find(params[:id])
    niveau_params = params.require(:niveau).permit(:niveau, :place)
    @niveau.update(niveau_params)
    redirect_to niveaus_path
  end

  def destroy
    @niveau = Niveau.find(params[:id])
    @niveau.destroy
    redirect_to niveaus_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/filieres_helper.rb
module FilieresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/niveaus_helper.rb
module NiveausHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/vagues_helper.rb
module VaguesHelper
end

app/views/niveaus/create.html.erb
<h1>Niveaus#create</h1>
<p>Find me in app/views/niveaus/create.html.erb</p>

app/views/niveaus/destroy.html.erb
<h1>Niveaus#destroy</h1>
<p>Find me in app/views/niveaus/destroy.html.erb</p>

app/views/niveaus/edit.html.erb
<h1>Niveaus#edit</h1>

<div class="container">
    <%= form_for @niveau do |n| %>

        <fieldset class="form-group">
            <label for="niveau">Niveau</label>
            <%= n.text_field :niveau %>
        </fieldset>

        <fieldset class="form-group">
            <label for="place">Nombre de place</label>
            <%= n.number_field :place %>
        </fieldset>

        <%= n.submit "Modifier", class: "btn btn-primary" %>
    <% end %>
    <div><a href="<%= niveaus_path %>">Voir tous les niveaux</a></div>
</div>

app/views/niveaus/index.html.erb
<h1>Niveaus#index</h1>
<table>
    <thead>
        <th>Niveau</th>
        <th>Nombres de place</th>
        <th></th>
        <th></th>
    </thead>
<% @niveaux.each do |n| %>
    <tr>
        <td><%= n.niveau %></td>
        <td><%= n.place %></td> 
        <td><%= link_to "Modifier", edit_niveau_path(n.id), class: "btn btn-info" %></td>
        <td>
            <a href="<%= niveau_path(n.id) %>" class="btn btn-danger" data-confirm="Êtes vous sur ?" data-method="DELETE">Supprimer</a>
        </td>
    </tr>
<% end %>
</table>
<a href="<%= new_niveau_path %>">Créer new niveau</a>

app/views/niveaus/new.html.erb
<div class="container">
    <%= form_for @niveau, url: niveaus_path  do |n| %>

        <fieldset class="form-group">
            <label for="niveau">Niveau</label>
            <%= n.text_field :niveau %>
        </fieldset>

        <fieldset class="form-group">
            <label for="place">Nombre de place</label>
            <%= n.number_field :place %>
        </fieldset>

        <%= n.submit "Create", class: "btn btn-primary" %>
    <% end %>
    <div><a href="<%= niveaus_path %>">Voir tous les niveaux</a></div>
</div>

app/views/niveaus/show.html.erb
<h1>Niveaus#show</h1>
<p>Find me in app/views/niveaus/show.html.erb</p>

app/views/niveaus/update.html.erb
<h1>Niveaus#update</h1>
<p>Find me in app/views/niveaus/update.html.erb</p>